### PR TITLE
renamed `partial` to `include` in documentation

### PR DESCRIPTION
**Pull request by akileez**
also renamed return statement from `partial` to `output`. 

``` js
return new Handlebars.SafeString(partials);
return new Handlebars.SafeString(output);
```

wasn't sure if this is what you meant.

### CODE REVIEW

**Comment by jonschlinkert** [comment]
thanks!

**Comment by doowb** [comment]
This doesn't work. The `var output` is defined inside the `map` function loop.
`var partials` is the results of `filepaths.map(...).join('\n');` and that's why it's being returned.

I do think that `partials` should be renamed to make it less confusing, but the change you made doesn't pass the jshint check.

**Comment by jonschlinkert** [comment]
Good catch @doowb. I can fix this now, unless you were already doing it

**Comment by doowb** [comment]
I fixed and pushed it up already.... https://github.com/helpers/handlebars-helper-include/commit/1f35239120343b0d2a6722cc3d127306cf63a81a

**Comment by jonschlinkert** [comment]
nvm lol

**Comment by jonschlinkert** [comment]
did you publish to npm?

**Comment by doowb** [comment]
I didn't publish to npm, I can do that in a minute.

**Comment by akileez** [comment]
Gentlemen, 

I apologize for the screw up. I was studying the partial helper and just scanned over `{{include}}` when I made the erroneous change.

**Comment by jonschlinkert** [comment]
no worries! seriously, I'm usually the one screwing things up lol

**Pull request merged**
